-- Миграция 0006: платежи Robokassa + состояние списания credits по job.

ALTER TABLE jobs
    ADD COLUMN IF NOT EXISTS credit_cost INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS credit_status VARCHAR(16) NOT NULL DEFAULT 'not_charged';

DO $$
BEGIN
    ALTER TABLE jobs
        ADD CONSTRAINT jobs_credit_status_check
        CHECK (credit_status IN ('not_charged', 'reserved', 'finalized', 'refunded'));
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS payments (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider            TEXT NOT NULL DEFAULT 'robokassa',
    provider_payment_id TEXT NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'pending',
    amount_rub          NUMERIC(10, 2) NOT NULL,
    credits_granted     INTEGER NOT NULL,
    receipt_email       TEXT NOT NULL,
    receipt_payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    pricing_version     TEXT NOT NULL,
    source_screen       TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at             TIMESTAMPTZ,
    failed_at           TIMESTAMPTZ,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT payments_status_check CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
    CONSTRAINT payments_amount_positive CHECK (amount_rub >= 0.01),
    CONSTRAINT payments_credits_positive CHECK (credits_granted >= 0),
    CONSTRAINT payments_provider_payment_id_unique UNIQUE (provider_payment_id)
);

CREATE INDEX IF NOT EXISTS idx_payments_user_created
    ON payments(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_payments_status_created
    ON payments(status, created_at DESC);
